# Generated by Django 5.2.7 on 2025-10-25 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
