# Generated by Django 5.2.7 on 2025-10-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_remove_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, default='sin_imagen.png', upload_to=''),
        ),
    ]
