# Generated by Django 5.2.7 on 2025-10-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_categoria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, default='sin_imagen.png', upload_to='categorias/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='sin_imagen.png', upload_to='productos/'),
        ),
    ]
