# Generated by Django 5.2.7 on 2025-10-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0004_alter_categoria_imagen_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
